.PHONY: clean All

All:
	@echo "----------Building project:[ Tachyon - Debug ]----------"
	@cd "Tachyon" && "$(MAKE)" -f  "Tachyon.mk"
clean:
	@echo "----------Cleaning project:[ Tachyon - Debug ]----------"
	@cd "Tachyon" && "$(MAKE)" -f  "Tachyon.mk" clean
